### ISSUE TITLE
Lost post author in slider?

### ISSUE THREAD

**Issue by mfgaede** [PressForward/PressForward-TurnKey-Theme#79]
Thanks for the awesome theme -- using it to set up a scholarly communication blog! Any ideas as to why the author of a given post got lost in the slider? The title shows up fine, then "By:" with nothing after it. Reset everything and it persists. Any thoughts?

[scholcomm.palni.org](http://scholcomm.palni.org)

**Comment by regan008** [comment]
Hi @mfgaede -- so glad you like the theme!

The author in the slider draws from the "item_author" custom field. This field is pulled in most of the time by PressForward (if you are using it) but occasionally the plugin won't find an author if it isn't coded correctly in the original post's rss feed.  You can always edit or add an author by filling in the "item_author" field in the custom fields on a post.  

If you don't see custom fields in the edit post page you probably just need to turn them on.  To do that go to "Screen Options" in the top right hand corner of the edit post page and make sure "Custom Fields" is checked.
![screen shot 2016-02-11 at 9 31 36 am](https://cloud.githubusercontent.com/assets/4553057/12978987/562a6254-d0a2-11e5-8aa0-bf76b2f3c5ec.png)

Once you've turned custom fields on, you'll see numerous fields below the post.  Look for the item_author field or add it from the drop down menu if it doesn't appear. 
![screen shot 2016-02-11 at 9 33 10 am](https://cloud.githubusercontent.com/assets/4553057/12979020/8f3a3ace-d0a2-11e5-9b6c-25cba80864d4.png)

Hope that helps let me know if you have further questions!

**Comment by mfgaede** [comment]
This is exactly what I was looking for, thank you so much! I've been a big fan of PressForward since the Library Publishing Forum last year and have been looking for an opportunity to use it. The theme is just the icing on the cake!

**Comment by regan008** [comment]
Excellent, I'm so glad it is working out for you! I plan to migrate the theme options to the WordPress customizer over the next 6 months and add a few new features so if you have any requests feel free to add an issue for a feature request!
